name: api
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.2
  crypto:
  pretty_dio_logger: ^1.3.1
  dio:
  firebase_database:

  auto_injector: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
