// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe83ToKWrjQwgl8pqndo2omJ-8fnoOqhI',
    appId: '1:26081040571:web:579acc104001c03f5af19e',
    messagingSenderId: '26081040571',
    projectId: 'marvel-app-307ce',
    authDomain: 'marvel-app-307ce.firebaseapp.com',
    databaseURL: 'https://marvel-app-307ce-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-app-307ce.appspot.com',
    measurementId: 'G-BZZVKFPR3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDErfUgxSE0wYQruXuRMbuxZ0QSgEeYln0',
    appId: '1:26081040571:android:51ef197598a2e3f35af19e',
    messagingSenderId: '26081040571',
    projectId: 'marvel-app-307ce',
    databaseURL: 'https://marvel-app-307ce-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-app-307ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5uaenoVuIuZnkJDGZ4aiPs93IARXFmRI',
    appId: '1:26081040571:ios:c04aa0184e2356c95af19e',
    messagingSenderId: '26081040571',
    projectId: 'marvel-app-307ce',
    databaseURL: 'https://marvel-app-307ce-default-rtdb.firebaseio.com',
    storageBucket: 'marvel-app-307ce.appspot.com',
    iosBundleId: 'com.example.marvelMobile',
  );
}
