name: design_system
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  masked_text: ^1.1.2
  result_dart:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
